lost/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("lostapp.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("markdownx/", include("markdownx.urls")),
]

# The code below is written with the help from ChatGPT, "How to include images in their posts created in CommonMark ", 2024-02-23
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lostapp/api/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from ..views import *
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

app_name = "lostapp_api"
urlpatterns = [
    path("authors/", authors, name="profile_list"),
    path("authors/<uuid:author_id>/", single_author, name="author"),
    path("authors/<uuid:author_id>/followers/", author_followers, name="followers"),
    path("authors/<uuid:author_id>/check_follow_status/<uuid:follower_id>", check_follow_status, name="check_follow_status"),
    path(
        "authors/<uuid:author_id>/followers/<uuid:follower_id>",
        single_follower,
        name="following",
    ),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/",
        single_post,
        name="single_post",
    ),
    path("authors/<uuid:author_id>/posts/", posts, name="posts"),
    path("authors/posts/all", all_posts, name="all_posts"),
    path(
        "authors/pending_follow_requests/",
        fetch_pending_follow_requests,
        name="fetch_pending_follow_requests",
    ),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/image/",
        image_post,
        name="post_image",
    ),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/comments/",
        comments,
        name="comments",
    ),
    path("authors/<uuid:author_id>/posts/<uuid:post_id>/likes/", likes, name="likes"),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/comments/<uuid:comment_id>/likes/",
        likes,
        name="comment_likes",
    ),
    path("authors/<uuid:author_id>/liked/", liked, name="liked"),
    path("authors/<uuid:author_id>/inbox/", inbox, name="inbox"),
    path(
        "authors/<uuid:author_id>/request/<path:follower_id>",
        pending_follow_request,
        name="pending_follow_request",
    ),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI:
    path(
        "schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="lostapp:lostapp_api:schema"),
        name="swagger-ui",
    ),
    path(
        "schema/redoc/",
        SpectacularRedocView.as_view(url_name="lostapp:lostapp_api:schema"),
        name="redoc",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lostapp/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "lostapp"
urlpatterns = [
    path("signup/", signup, name="signup"),
    path("authors/<uuid:author_id>/", author_profile, name="author"),
    path("", index, name="index"),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/",
        SinglePostView.as_view(),
        name="single_post",
    ),
    path("authors/<uuid:author_id>/posts/create/", post_create, name="post_create"),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/edit/",
        post_edit,
        name="single_post_edit",
    ),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/comments/",
        CommentsView.as_view(),
        name="comments",
    ),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/comments/<uuid:comment_id>/",
        CommentsView.as_view(),
        name="single_comments",
    ),
    path("edit_profile/", edit_profile, name="edit_profile"),
    path(
        "authors/<uuid:author_id>/profile_change/",
        profile_change,
        name="profile_change",
    ),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/image/",
        display_post_image,
        name="post_image",
    ),


    path("api/", include("lostapp.api.urls")),
    path("authors/", author_list, name="author_list"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lostapp/views.py
import base64
import json
import logging
from functools import wraps
from urllib.parse import urljoin, unquote
from uuid import UUID

import requests
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.paginator import Paginator
from django.core.validators import validate_email
from django.db import IntegrityError
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from drf_spectacular.utils import extend_schema, OpenApiExample, OpenApiParameter
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import *
from django.contrib.auth.decorators import login_required
logger = logging.getLogger(__name__)


def index(request):
    fetch_github()
    context = {}
    if request.user.is_authenticated:
        # follow_requests = Inbox.objects.filter(author=request.user.author, type=Inbox.Type.FOLLOW)
        follow_requests = Inbox.objects.filter(author=request.user.author)
        context["follow_requests"] = follow_requests
    return render(request, "home.html", context)


def signup(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        display_name = request.POST["display_name"]
        github = request.POST["github"]

        # Validate email format
        try:
            validate_email(email)
        except ValidationError:
            # Render the signup page with an error message
            return render(
                request,
                "registration/signup.html",
                {"error_message": "Invalid email format."},
            )

        # Check if the email is already associated with an existing account
        if User.objects.filter(email=email).exists():
            # Render the signup page with an error message
            return render(
                request,
                "registration/signup.html",
                {
                    "error_message": "Email is already associated with an existing account."
                },
            )

        # Check if the username is already taken
        if User.objects.filter(username=username).exists():
            # Render the signup page with an error message
            return render(
                request,
                "registration/signup.html",
                {"error_message": "Username is already taken."},
            )

        # # Check if the display name is already taken
        # if Author.objects.filter(display_name=display_name).exists():
        #     # Render the signup page with an error message
        #     return render(request, 'registration/signup.html', {'error_message': 'Display name is already taken.'})

        # Check if profile image is provided
        if "profile_image" in request.FILES:
            profile_image = request.FILES["profile_image"]
        else:
            # Define the path to the default image
            profile_image = "../media/default.jpg"

        try:
            # Create a new User instance
            user = User.objects.create_user(
                username=username, email=email, password=password
            )

            # Create a new Author instance
            author = Author.objects.create(
                user=user,
                display_name=display_name,
                github=github,
                profile_image=profile_image,
            )

            # Redirect to the login page
            return redirect("login")

        except IntegrityError:
            # Render the signup page with an error message
            return render(
                request,
                "registration/signup.html",
                {"error_message": "An error occurred. Please try again."},
            )

    return render(request, "registration/signup.html")


def author_profile(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    return render(request, "authors/profile.html", {"author": author})


def send_follow_request(request):
    if request.method == "POST":
        target_author_id = request.POST.get("author_id")
        target_author = get_object_or_404(Author, id=target_author_id)
        current_user_profile = request.user.author

        if (
            current_user_profile != target_author
        ):  # Ensure the user is not trying to follow themselves
            target_author.pending_follow_requests.add(current_user_profile)
            return JsonResponse(
                {"status": "success", "message": "Follow request sent successfully"}
            )
        else:
            return JsonResponse(
                {
                    "status": "error",
                    "message": "You cannot send a follow request to yourself",
                }
            )


@extend_schema(
    exclude=True,
)
@api_view(["GET"])
def fetch_pending_follow_requests(request):
    if request.method == "GET" and request.user.is_authenticated:
        current_user = request.user.author
        current_user_profile = get_object_or_404(Author, id=current_user.id)
        pending_requests = current_user_profile.pending_follow_requests.all()
        # Serialize pending requests data as needed
        pending_requests_data = [
            {
                "authorId": current_user.id,
                "actor": pending.id,
                "displayName": pending.display_name,
                "profileImage": pending.profile_image.url,
                "github": pending.github,
                "date_joined": pending.date_joined.strftime("%Y-%m-%d %H:%M:%S"),
            }
            for pending in pending_requests
        ]

        return Response(pending_requests_data)
    else:
        return None


class SinglePostView(View):
    """Class for handling requests for single posts."""

    def get(self, request, author_id, post_id):
        post = get_object_or_404(Post, id=post_id, author_id=author_id)
        return render(
            request,
            "single_post/index.html",
        )


def author_list(request):
    return render(request, "authors/author_list.html")


def post_create(request, author_id):
    """Function for rendering post creation page."""
    return render(request, "posts/create_post.html", context={"author_id": author_id})


def post_edit(request, author_id, post_id):
    """Function for rendering edit post page. Will not allow user to
    edit posts from other users.
    """
    # Only allow editing own posts.
    post = get_object_or_404(Post, id=post_id, author_id=author_id)

    if request.user.author.id != post.author_id:
        return HttpResponse("You are not allowed to edit this post.", status=403)

    return render(request, "posts/edit_post.html")


def profile_change(request, author_id):
    """API function for saving change in user profile."""
    author = get_object_or_404(Author, id=author_id)
    if request.method == "POST":
        # Overwrite fields only if input provided.
        if request.POST.get("display_name"):
            author.display_name = request.POST.get("display_name")
        if request.POST.get("github"):
            author.github = request.POST.get("github")

        # Add author_id before picture name to make sure not overwrite same images
        # for different users in case the picture has the same name.
        new_profile_image = request.FILES.get("profile_image")
        if new_profile_image:
            author.profile_image = SimpleUploadedFile(
                f"{author_id}-{new_profile_image.name}", new_profile_image.read()
            )
        author.save()

        # Redirect to profile page
        return redirect(f"/authors/{author_id}")


def edit_profile(request):
    """Function for rendering edit profile page."""
    author = get_object_or_404(Author, id=request.user.author.id)
    return render(request, "authors/edit_profile.html", {"author": author})


def display_post_image(request, author_id, post_id):
    post = get_object_or_404(Post, id=post_id, author_id=author_id)
    format, imgstr = post.content.split(";base64,")
    if post.content_format == Post.Format.IMAGE:
        image_decoded = base64.b64decode(imgstr)
        return HttpResponse(image_decoded, content_type="image/jpg")


class CommentsView(View):
    """Class for handling requests for comments."""

    def post(self, request, author_id, post_id):
        post = get_object_or_404(Post, id=post_id)
        comment_content = request.POST.get("comment_content", "")
        if comment_content:
            Comment.objects.create(
                post=post,
                author=request.user.author,
                comment=comment_content,
            )
            return HttpResponseRedirect(
                reverse("lostapp:single_post", args=[author_id, post_id]), status=303
            )
        else:
            return HttpResponse("Error adding comment", status=400)

    def get(self, request, author_id, post_id):
        post = get_object_or_404(Post, id=post_id)
        comments_list = post.comments.all().order_by("-published")
        page = request.GET.get("page", 1)
        size = request.GET.get("size", 10)
        paginator = Paginator(comments_list, size)
        page_object = paginator.get_page(page)
        host = settings.HOSTNAME
        comments_data = []

        for comment in page_object:
            common_url = urljoin(
                host, reverse("lostapp:author", args=[comment.author.id])
            )
            comments_data.append(
                {
                    "type": "comment",
                    "author": {
                        "type": "author",

lostapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet"href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <title>lostapp</title>
    {% block script %}{% endblock script %}
</head>
<body>
<section class="hero is-small is-success mb-2">
    <div class="hero-body">
        <h1 class="title is-2"><a href="{% url 'lostapp:index' %}">Lostapp</a></h1>
    </div>
</section>

<div class="container">
    <div class="columns">

        {% block content %}

        {% endblock content %}

    </div>
</div>
</body>
</html>

lostapp/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block script %}



    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script src="{% static 'lostapp/js/feed.js' %}"></script>
    <script src="{% static 'lostapp/js/utility.js' %}"></script>
    <meta name="author-id" content="{{ user.author.id }}">
{% endblock %}

{% block title %}
    <h1 class="title">Home</h1>
{% endblock %}

{% block content %}
    <div id="user" style="display: none;" data-logged-in-author-id="{{ user.author.id }}"></div>
    {% if user.is_authenticated and user.author.is_approved %}
        <div class="columns">
            <div class="column is-4">
                <aside class="menu">
                    <p class="menu-label">Navigation</p>
                    <ul class="menu-list">
                        <li><a href="{% url 'lostapp:author' author_id=user.author.id %}">Profile</a></li>
                        <li><a href="{% url 'lostapp:author_list' %}">Authors</a></li>
                        <li><a href="{% url 'lostapp:post_create' author_id=user.author.id %}">Create Post</a></li>
                        <li>
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="button is-danger">Log Out</button>
                            </form>
                        </li>
                    </ul>
                </aside>
            </div>
            <div class="column">
                <h2 class="subtitle">{{ user.author.display_name }}'s Stream</h2>
                <div id="main-stream"></div>
                <ul class="post-list"></ul>
                <style>
                    .author-name {
                        font-size: 1.4em;
                        font-weight: bold;
                    }

                    .subtitle {
                        font-size: 1.6em;
                        font-weight: bold;
                        margin-top: 1em;
                    }

                    .post-title {
                        font-size: 0.85em;
                        font-weight: bold;
                    }

                    .post-content {
                        padding: 10px;
                    }

                    .post-image {
                        padding: 5px;
                        max-width: 500px;
                        max-height: 400px;
                    }

                    .menu-label {
                        font-size: 1.2em;
                        font-weight: bold;
                        margin-top: 1.5em;
                    }
                </style>
                </ul>
            </div>
            <!-- <div class="column">
                <h2 class="subtitle">Follow requests</h2>
                <ul>
                {% for follow_request in user.author.pending_follow_requests.all %}
                    <li>Follow request from {{ follow_request.user}}</li>
                    <button onclick="accept_request('{{ user.author.id }}', '{{ follow_request.id}}')"
                    data-author-id="{{ user.author.id }}"
                    class="button is-success request-button"
                    data-action="accept">
                    
                    Accept</button>

                    <button onclick="decline_request('{{ user.author.id }}', '{{ follow_request.id}}')"
                    data-author-id="{{ user.author.id }}"
                    class="button is-danger request-button"
                    data-action="decline">
                        Decline</button>
                {% empty %}
                    <li>No follow requests.</li>
                {% endfor %}
                </ul>
            </div> -->

            <div class="column">
                <h2 class="subtitle">Follow requests</h2>
                <ul id="follow-request-list">
                    <!-- List will be populated dynamically by JavaScript -->
                </ul>
            </div>
            


        </div>

    {% elif user.is_authenticated and not user.author.is_approved %}
        <p>Your account is pending approval by the server admin. Please wait for approval.</p>
        <form action="{% url 'logout' %}" method="post">
            <ul class="post-list"></ul>
            {% csrf_token %}
            <button type="submit">Log Out</button>
        </form>
    {% else %}
        <div class="column">
                    <div class="column is-4">
                        <div class="login-button-container">
                            <a href="{% url 'login' %}" class="button is-primary">Log In</a>
                            <a href="{% url 'lostapp:signup' %}" class="button is-primary">Sign Up</a>
                        </div>
                    </div>
                    </div>
                </div>
                <h2 class="subtitle">Public Stream</h2>
                <div id="main-stream"></div>
                <ul class="post-list"></ul>
        </div>
    {% endif %}
{% endblock %}