lost/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("lostapp.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("markdownx/", include("markdownx.urls")),
]

# The code below is written with the help from ChatGPT, "How to include images in their posts created in CommonMark ", 2024-02-23
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lostapp/api/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from ..views import *
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

app_name = "lostapp_api"
urlpatterns = [
    path("authors/", authors, name="profile_list"),
    path("authors/<uuid:author_id>/", single_author, name="author"),
    path("authors/<uuid:author_id>/followers/", author_followers, name="followers"),
    path("authors/<uuid:author_id>/check_follow_status/<uuid:follower_id>", check_follow_status, name="check_follow_status"),
    path(
        "authors/<uuid:author_id>/followers/<uuid:follower_id>",
        single_follower,
        name="following",
    ),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/",
        single_post,
        name="single_post",
    ),
    path("authors/<uuid:author_id>/posts/", posts, name="posts"),
    path("authors/posts/all", all_posts, name="all_posts"),
    path(
        "authors/pending_follow_requests/",
        fetch_pending_follow_requests,
        name="fetch_pending_follow_requests",
    ),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/image/",
        image_post,
        name="post_image",
    ),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/comments/",
        comments,
        name="comments",
    ),
    path("authors/<uuid:author_id>/posts/<uuid:post_id>/likes/", likes, name="likes"),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/comments/<uuid:comment_id>/likes/",
        likes,
        name="comment_likes",
    ),
    path("authors/<uuid:author_id>/liked/", liked, name="liked"),
    path("authors/<uuid:author_id>/inbox/", inbox, name="inbox"),
    path(
        "authors/<uuid:author_id>/request/<path:follower_id>",
        pending_follow_request,
        name="pending_follow_request",
    ),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI:
    path(
        "schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="lostapp:lostapp_api:schema"),
        name="swagger-ui",
    ),
    path(
        "schema/redoc/",
        SpectacularRedocView.as_view(url_name="lostapp:lostapp_api:schema"),
        name="redoc",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lostapp/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "lostapp"
urlpatterns = [
    path("signup/", signup, name="signup"),
    path("authors/<uuid:author_id>/", author_profile, name="author"),
    path("", index, name="index"),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/",
        SinglePostView.as_view(),
        name="single_post",
    ),
    path("authors/<uuid:author_id>/posts/create/", post_create, name="post_create"),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/edit/",
        post_edit,
        name="single_post_edit",
    ),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/comments/",
        CommentsView.as_view(),
        name="comments",
    ),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/comments/<uuid:comment_id>/",
        CommentsView.as_view(),
        name="single_comments",
    ),
    path("edit_profile/", edit_profile, name="edit_profile"),
    path(
        "authors/<uuid:author_id>/profile_change/",
        profile_change,
        name="profile_change",
    ),
    path(
        "authors/<uuid:author_id>/posts/<uuid:post_id>/image/",
        display_post_image,
        name="post_image",
    ),


    path("api/", include("lostapp.api.urls")),
    path("authors/", author_list, name="author_list"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lostapp/views.py
import base64
import json
import logging
from functools import wraps
from urllib.parse import urljoin, unquote
from uuid import UUID

import requests
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.paginator import Paginator
from django.core.validators import validate_email
from django.db import IntegrityError
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from drf_spectacular.utils import extend_schema, OpenApiExample, OpenApiParameter
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import *
from django.contrib.auth.decorators import login_required
logger = logging.getLogger(__name__)


def index(request):
    fetch_github()
    context = {}
    if request.user.is_authenticated:
        # follow_requests = Inbox.objects.filter(author=request.user.author, type=Inbox.Type.FOLLOW)
        follow_requests = Inbox.objects.filter(author=request.user.author)
        context["follow_requests"] = follow_requests
    return render(request, "home.html", context)


def signup(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        display_name = request.POST["display_name"]
        github = request.POST["github"]

        # Validate email format
        try:
            validate_email(email)
        except ValidationError:
            # Render the signup page with an error message
            return render(
                request,
                "registration/signup.html",
                {"error_message": "Invalid email format."},
            )

        # Check if the email is already associated with an existing account
        if User.objects.filter(email=email).exists():
            # Render the signup page with an error message
            return render(
                request,
                "registration/signup.html",
                {
                    "error_message": "Email is already associated with an existing account."
                },
            )

        # Check if the username is already taken
        if User.objects.filter(username=username).exists():
            # Render the signup page with an error message
            return render(
                request,
                "registration/signup.html",
                {"error_message": "Username is already taken."},
            )

        # # Check if the display name is already taken
        # if Author.objects.filter(display_name=display_name).exists():
        #     # Render the signup page with an error message
        #     return render(request, 'registration/signup.html', {'error_message': 'Display name is already taken.'})

        # Check if profile image is provided
        if "profile_image" in request.FILES:
            profile_image = request.FILES["profile_image"]
        else:
            # Define the path to the default image
            profile_image = "../media/default.jpg"

        try:
            # Create a new User instance
            user = User.objects.create_user(
                username=username, email=email, password=password
            )

            # Create a new Author instance
            author = Author.objects.create(
                user=user,
                display_name=display_name,
                github=github,
                profile_image=profile_image,
            )

            # Redirect to the login page
            return redirect("login")

        except IntegrityError:
            # Render the signup page with an error message
            return render(
                request,
                "registration/signup.html",
                {"error_message": "An error occurred. Please try again."},
            )

    return render(request, "registration/signup.html")


def author_profile(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    return render(request, "authors/profile.html", {"author": author})


def send_follow_request(request):
    if request.method == "POST":
        target_author_id = request.POST.get("author_id")
        target_author = get_object_or_404(Author, id=target_author_id)
        current_user_profile = request.user.author

        if (
            current_user_profile != target_author
        ):  # Ensure the user is not trying to follow themselves
            target_author.pending_follow_requests.add(current_user_profile)
            return JsonResponse(
                {"status": "success", "message": "Follow request sent successfully"}
            )
        else:
            return JsonResponse(
                {
                    "status": "error",
                    "message": "You cannot send a follow request to yourself",
                }
            )


@extend_schema(
    exclude=True,
)
@api_view(["GET"])
def fetch_pending_follow_requests(request):
    if request.method == "GET" and request.user.is_authenticated:
        current_user = request.user.author
        current_user_profile = get_object_or_404(Author, id=current_user.id)
        pending_requests = current_user_profile.pending_follow_requests.all()
        # Serialize pending requests data as needed
        pending_requests_data = [
            {
                "authorId": current_user.id,
                "actor": pending.id,
                "displayName": pending.display_name,
                "profileImage": pending.profile_image.url,
                "github": pending.github,
                "date_joined": pending.date_joined.strftime("%Y-%m-%d %H:%M:%S"),
            }
            for pending in pending_requests
        ]

        return Response(pending_requests_data)
    else:
        return None


class SinglePostView(View):
    """Class for handling requests for single posts."""

    def get(self, request, author_id, post_id):
        post = get_object_or_404(Post, id=post_id, author_id=author_id)
        return render(
            request,
            "single_post/index.html",
        )


def author_list(request):
    return render(request, "authors/author_list.html")


def post_create(request, author_id):
    """Function for rendering post creation page."""
    return render(request, "posts/create_post.html", context={"author_id": author_id})


def post_edit(request, author_id, post_id):
    """Function for rendering edit post page. Will not allow user to
    edit posts from other users.
    """
    # Only allow editing own posts.
    post = get_object_or_404(Post, id=post_id, author_id=author_id)

    if request.user.author.id != post.author_id:
        return HttpResponse("You are not allowed to edit this post.", status=403)

    return render(request, "posts/edit_post.html")


def profile_change(request, author_id):
    """API function for saving change in user profile."""
    author = get_object_or_404(Author, id=author_id)
    if request.method == "POST":
        # Overwrite fields only if input provided.
        if request.POST.get("display_name"):
            author.display_name = request.POST.get("display_name")
        if request.POST.get("github"):
            author.github = request.POST.get("github")

        # Add author_id before picture name to make sure not overwrite same images
        # for different users in case the picture has the same name.
        new_profile_image = request.FILES.get("profile_image")
        if new_profile_image:
            author.profile_image = SimpleUploadedFile(
                f"{author_id}-{new_profile_image.name}", new_profile_image.read()
            )
        author.save()

        # Redirect to profile page
        return redirect(f"/authors/{author_id}")


def edit_profile(request):
    """Function for rendering edit profile page."""
    author = get_object_or_404(Author, id=request.user.author.id)
    return render(request, "authors/edit_profile.html", {"author": author})


def display_post_image(request, author_id, post_id):
    post = get_object_or_404(Post, id=post_id, author_id=author_id)
    format, imgstr = post.content.split(";base64,")
    if post.content_format == Post.Format.IMAGE:
        image_decoded = base64.b64decode(imgstr)
        return HttpResponse(image_decoded, content_type="image/jpg")


class CommentsView(View):
    """Class for handling requests for comments."""

    def post(self, request, author_id, post_id):
        post = get_object_or_404(Post, id=post_id)
        comment_content = request.POST.get("comment_content", "")
        if comment_content:
            Comment.objects.create(
                post=post,
                author=request.user.author,
                comment=comment_content,
            )
            return HttpResponseRedirect(
                reverse("lostapp:single_post", args=[author_id, post_id]), status=303
            )
        else:
            return HttpResponse("Error adding comment", status=400)

    def get(self, request, author_id, post_id):
        post = get_object_or_404(Post, id=post_id)
        comments_list = post.comments.all().order_by("-published")
        page = request.GET.get("page", 1)
        size = request.GET.get("size", 10)
        paginator = Paginator(comments_list, size)
        page_object = paginator.get_page(page)
        host = settings.HOSTNAME
        comments_data = []

        for comment in page_object:
            common_url = urljoin(
                host, reverse("lostapp:author", args=[comment.author.id])
            )
            comments_data.append(
                {
                    "type": "comment",
                    "author": {
                        "type": "author",

lostapp/templates/authors/author_list.html
{% extends 'base.html' %}
{% load static %}
{% block script %}
    <script src="{% static 'lostapp/js/author_list.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="column" id="profile">
    </div>

{% endblock content %}

lostapp/templates/authors/edit_profile.html
<!-- lost/lostapp/templates/authors/base.html -->
{% extends "base.html" %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
    <div class="column" id="profile">
    <h2 class="subtitle">Edit Profile:</h2>
    <form method="post" action="{% url 'lostapp:profile_change' author_id=author.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="display_name">Display name:</label>
        <input class="input is-primary" placeholder="Leave field empty if you don't want to change it" type="text" name="display_name">
        <br></br>
		<label for="github">Github link:</label>
        <input class="input is-primary" placeholder="Leave field empty if you don't want to change it" type="text" name="github">
        <br></br>
		<label for="profile_image">Profile image:</label>
        <input type="file" id="profile_image" name="profile_image">
		<br>
		<br>
        <button class="button is-primary is-outlined" type="submit">Submit changes</button>
    </form>
    </div>
{% endblock %}

lostapp/templates/authors/profile.html
<!-- lost/lostapp/templates/authors/base.html -->
{% extends "base.html" %}
{% load static %}

{% block script %}
    <script>
        userId = '{{ user.author.id }}';
        authorId = '{{ author.id }}';
        userUrl = "{{ user.author.host }}api/authors/{{ user.author.id }}";
    </script>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    <script src="{% static 'lostapp/js/utility.js' %}"></script>
    <script src="{% static 'lostapp/js/profile.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <meta name="author-id" content="{{ author.id }}">
    <meta name="author-url" content="{{ author.host }}api/authors/{{ author.id }}">
{% endblock %}

{% block content %}
    <div id="user" style="display: none;" data-logged-in-author-id="{{ user.author.id }}"></div>
    <div class="column" id="posts">
        <div class="column" id="profile"></div>
    </div>

    <div id="follow">
        <div></div>
        <div>
            <br>
            <div class="block">
                <a href="{% url 'lostapp:author_list' %}">
                    <button class="button is-dark is-outlined is-fullwidth">
                        All Profiles
                    </button>
                </a>
            </div>
            <!-- <button onclick="follow(authorId,userUrl)"
                    class="button
            is-success follow-button"
                    data-action="follow"
                    data-author-id=
                            "{{ author.id }}">
                Follow
            </button>
            <button onclick="unfollow(authorId,userUrl)"
                    class="button is-danger follow-button" data-action="unfollow" data-author-id=
                            "{{ author.id }}"
                    style="display: none;">
                Unfollow
            </button> -->

            <button onclick="follow(authorId, userUrl)"
            class="button is-success follow-button"
            data-action="follow"
            data-author-id="{{ author.id }}">
        Follow
    </button>
    <button onclick="unfollow(authorId, userUrl)"
            class="button is-danger follow-button"
            data-action="unfollow"
            data-author-id="{{ author.id }}"
            style="display: none;">
        Unfollow
    </button>
    <button onclick="sendPendingRequest(authorId, userUrl)"
            class="button is-warning pending-button"
            data-action="pending"
            data-author-id="{{ author.id }}"
            style="display: none;">
        Pending
    </button>

            <br>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{ author.display_name }} follows:
        </h3>
        <div class="content">
            <ul>
                {% for following in author.follows.all %}
                    <li>
                        <a href="{% url 'lostapp:author' author_id=following.id %}">
                            {{ following.display_name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{ author.display_name }} is followed by:
        </h3>
        <div class="content">
            <ul>
                {% for follower in author.followed_by.all %}
                    <li>
                        <a href="{% url 'lostapp:author' author_id=follower.id %}">
                            {{ follower.display_name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <style>
        .profile_image img {
            width         : 10em;
            height        : 10em;
            object-fit    : cover;
            border-radius : 50%;
            margin-bottom : 1em;
        }
    </style>
{% endblock %}